public enum GameState {
    SENDING_CATEGORY,
    CHECKING_CATEGORY,
    WAITING_FOR_OTHER_PLAYER_TO_SET_CATEGORY,
    SENDING_QUESTION,
    CHECKING_ANSWER,
    RESULT_SENT,
    WAITING_FOR_OTHER_PLAYER_TO_BE_DONE,
    GAME_DONE
}
